version: 2.1

executors:
  main-checker:
    docker:
      - image: cimg/base:stable-20.04

jobs:
  build-main:
    executor: main-checker
    steps:
      - run: echo "Success"

workflows:
  version: 2
  build-main:
    jobs:
      - build-main:
          filters:
            branches:
              only: main
