version: 2.1

executors:
  master-checker:
    docker:
      - image: cimg/base:stable-20.04

jobs:
  build-master:
    executor: master-checker
    steps:
      - run: echo "Success"

workflows:
  version: 2
  build-master:
    jobs:
      - build-master:
          filters:
            branches:
              only: master
